### ISSUE TITLE
BUG: client 3.11.0 problems on Linux Mint (Mate / Cinnamon)

### ISSUE THREAD

**Issue by stullekovski** [flathub/com.nextcloud.desktopclient.nextcloud#140]
Hi,

just to let you know, there are some issues with the latest desktop client version.

Mint Cinnamon: icon is broken
https://github.com/nextcloud/desktop/issues/6312

Mint Mate: not starting at all
https://github.com/nextcloud/desktop/issues/6313

Hope you can figure it out.
Thanks a lot.

**Comment by narFnarF** [comment]
I have the same problem. I'm also on Linux Mint MATE edition.

How to reproduce:
1. Launching the flatpak version

What happens:
Nextcloud hangs and eat a lot of CPU. The Nextcloud window never appears. The nextcloud icon doesn't show up in the tray. The only way to end the CPU eating is to kill the process.

Expected result:
The Nextcloud window appears.

Other info:
I tried to launch via the command line. Here's the log:
```
# flatpak run com.nextcloud.desktopclient.nextcloud
Qt: Session management error: Could not open network socket
nextcloud.gui.application: Migrating old config from "/home/narf/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/narf/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/narf/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/narf/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("home and data_Nextcloud_sync.log", "Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "home and data_Nextcloud_sync.log" also failed
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed

** (process:3668): WARNING **: 06:08:21.118: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.143: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.166: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.192: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.219: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.239: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.259: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.282: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.300: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.320: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts

** (process:3668): WARNING **: 06:08:21.354: Failed to connect to bus: Impossible de créer le connecteur : Trop de fichiers ouverts
```
And then it keeps repeating this warning 10+ times per second 😅

My system is in French. This part of the error message `Impossible de créer le connecteur : Trop de fichiers ouverts` means something like: _"Impossible to create the connector: Too many files open."_

**Comment by stullekovski** [comment]
Hi, I did a downgrade of the flatpak:

flatpak list
flatpak remote-info --log flathub com.nextcloud.desktopclient.nextcloud
sudo flatpak update --commit=08e53a14920ec5b626ff13a7c65f41185241cbcdd5a3e5dd5646a27393433236 com.nextcloud.desktopclient.nextcloud

https://itsfoss.com/downgrade-flatpak-packages/

**Comment by arielnmz** [comment]
Same problem here:

```
** (process:9725): WARNING **: 04:20:09.350: Failed to connect to bus: Unable to create socket: Too many open files
```

It goes on forever until my desktop crashes back to the login manager, reverting to `08e53a14920ec5b626ff13a7c65f41185241cbcdd5a3e5dd5646a27393433236` fixed the issue (but I still got the failed to migrate window on the first run)

**Comment by ekasprzak** [comment]
Seems like it is not actually related to either v 3.11 or Mint or any specific DE.

Saw it in various places for people using various distros and DEs (Fedora/GNOME here).

There are three 3.11 flatpak builds for now:
```
    Commit: 5506eb1faf63ea37d4c4c37a75514519e77bee45914570dae5a95fe6f01ba24b
    Parent: d93a7217c22261f9bacb864c1df429976debbbd7f62673e21e1c26f3ce514286
   Subject: Update 0.14.1.tar.gz to 0.14.2 (daf49ade)
      Date: 2023-12-20 15:42:41 +0000
   History: 

    Commit: d93a7217c22261f9bacb864c1df429976debbbd7f62673e21e1c26f3ce514286
   Subject: Update 0.14.1.tar.gz to 0.14.2 (646b3d37)
      Date: 2023-12-19 05:36:29 +0000

    Commit: cfb04ee73a6ede816ff68df468b1372461d4bb9c8ced24c9747328247b69efec
   Subject: Update desktop.git to 3.11.0 (03b171c4)
      Date: 2023-12-12 13:10:35 +0000
```

Downgrading to "Update desktop.git to 3.11.0 (03b171c4)" or "Update 0.14.1.tar.gz to 0.14.2 (646b3d37)" - no issue, nextclod runs and shows the icon, everything seems to be fine.

So, looks like there is sth wrong with latest build from 20.12, my guess would be PR #130 and that is what causes the issue.
